### ISSUE TITLE
Rating on reply

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [pixelgrade/comments-ratings#9]
Currently: replying to a review includes a star rating which is calculated in the total review rating.
 I want it to be: replying to a review (so a comment to a review) should not be calculated in the review value (the reply should have no stars, not counted as an additional review)

Is there any option for that or It is a feature in premium version or any idea you can provide on this ?

**Comment by raduconst** [comment]
I will copy here the code that you sent to me in the ticket and we'll look at it for a future update :-)

```
class  PixReviewsPlugin{
function get_average_rating( $post_id = null, $decimals = 2 ) {

   if ( empty( $post_id ) ) {
      $post_id = get_the_ID();
   }

   $comments = get_comments( apply_filters( 'some_filter', array(
      'post_id'  => $post_id,
      'meta_key' => 'pixrating',
      'status'   => 'approve'
   ) ) );

   if ( empty( $comments ) ) {
      return false;
   }

   $total = 0;
   foreach ( $comments as $comment ) {
      $current_rating  = get_comment_meta( $comment->comment_ID, 'pixrating', true );
      $total = $total + (double) $current_rating;
   }

   $average = $total / count( $comments );

   return number_format( $average, $decimals );
}
}
```

Can be done by overriding display_rating and output_review_fields functions and using get_comments_number, comment_form_logged_in_after, comment_form_after_fields and  comment_text hooks.

**Comment by PrafullaKumarSahu** [comment]
add_action( 'comment_form_logged_in_after', array( $pixreviews_plugin_mod, 'output_review_fields' ) ); // Guest
    add_action( 'comment_form_after_fields', array( $pixreviews_plugin_mod, 'output_review_fields' ) ); // Guest
    add_action( 'comment_text', array( $pixreviews_plugin_mod, 'display_rating' ) ); 

and 

To count the original reviews use get_comments_number filter.

display_rating() and output_review_fields() functions are from PixReviewsPlugin class . I think this is another way we can do this, actually I am using it not modifying the original plugin . If I can do something else related to this, please let me know.
